[mcp_servers.nuxt]
enabled = true
url = "https://nuxt.com/mcp"

[mcp_servers.nuxt_ui]
enabled = true
url = "https://ui.nuxt.com/mcp"

[mcp_servers.nuxt_seo]
enabled = true
url = "https://nuxtseo.com/mcp"

[mcp_servers.mapbox_devkit]
url = "https://mcp-devkit.mapbox.com/mcp"
