import { existsSync } from "node:fs";
import { isAbsolute, resolve } from "node:path";
import { createJiti } from "jiti";

import { validateDirectusConfig } from "./index";

/**
 * Resolves an optional consumer-owned Directus configuration source.
 *
 * @param rootDir Nuxt application root.
 * @param configFile Absolute or root-relative configuration path.
 * @returns Absolute source path, or undefined when source discovery is disabled or absent.
 */
export function resolveDirectusConfigFile(
  rootDir: string,
  configFile: string | false
): string | undefined {
  if (configFile === false) return undefined;
  const path = isAbsolute(configFile) ? configFile : resolve(rootDir, configFile);
  return existsSync(path) ? path : undefined;
}

/**
 * Loads and validates the complete executable Directus config during Nuxt module setup.
 *
 * @param configFile Consumer config source path, when present.
 * @returns Validated Directus configuration.
 */
export async function loadDirectusConfigSource(configFile?: string) {
  if (!configFile) return validateDirectusConfig({});
  const jiti = createJiti(import.meta.url, { interopDefault: true });
  return validateDirectusConfig(await jiti.import(configFile, { default: true }));
}

/**
 * Loads shared Directus configuration for Nuxt dependency discovery.
 *
 * @param rootDir Nuxt application root.
 * @param configFile Root-relative or absolute consumer configuration source path.
 * @returns Validated shared configuration, or undefined when no source is configured.
 */
export async function getResolvedDirectusConfigFromSource(
  rootDir: string,
  configFile: string | false = "directus.config.ts"
) {
  const resolvedConfigFile = resolveDirectusConfigFile(rootDir, configFile);
  return resolvedConfigFile ? loadDirectusConfigSource(resolvedConfigFile) : undefined;
}

/**
 * Generates a virtual module that exports the client safe consumer Directus config without serializing it.
 *
 * @param configFile Consumer config source path, when present.
 * @returns Virtual module source.
 */
export function generateDirectusRuntimeConfigSource(configFile?: string): string {
  return configFile
    ? `import config from ${JSON.stringify(configFile)};\nimport { directusConfigSchema, directusPublicConfigSchema } from '@onderwijsin/nuxt-directus-config/schema';\nexport default directusPublicConfigSchema.parse(directusConfigSchema.parse(config));\n`
    : "export default {};\n";
}

/**
 * Generates the Nitro-only module that exposes the complete executable Directus config.
 *
 * @param configFile Consumer config source path, when present.
 * @returns Server-only virtual module source.
 */
export function generateDirectusServerConfigSource(configFile?: string): string {
  return configFile
    ? `import config from ${JSON.stringify(configFile)};\nimport { validateDirectusConfig } from '@onderwijsin/nuxt-directus-config/config';\nexport default validateDirectusConfig(config);\n`
    : "export default {};\n";
}

/**
 * Generates the Nitro-only declaration for the complete Directus configuration module.
 *
 * @returns Source for Nuxt's generated Nitro type declaration.
 */
export function generateDirectusServerConfigDeclarationSource(): string {
  return `// Generated by @onderwijsin/nuxt-directus-config
import type { ResolvedDirectusConfig } from "../schema";

declare const config: ResolvedDirectusConfig;
export default config;
`;
}
