// Generated by @onderwijsin/nuxt-theme-customizer
declare module "nuxt/schema" {
  interface RuntimeConfig {
    themeCustomizerGoogleFontsApiKey?: string;
  }

  interface PublicRuntimeConfig {
    themeCustomizer: {
      groups: Record<string, string[]>;
      googleFonts?: {
        families: string[];
      };
      defaults?: {
        font?: string;
        radius?: number;
        [group: string]: string | number | undefined;
      };
    };
  }

  interface AppConfig {
    ui: {
      colors: Record<string, string>;
      radius: number;
    };
  }
}

export {};
