import type { UserFieldSelection } from "@onderwijsin/nuxt-directus-config/schema";

function generateUserFieldsType(fields: readonly UserFieldSelection[]): string {
  const values = fields.map((field) => {
    if (typeof field === "string") return JSON.stringify(field);
    const [relation, nestedFields] = Object.entries(field)[0] ?? [];
    return `{ readonly ${JSON.stringify(relation)}: ${generateUserFieldsType(nestedFields ?? [])} }`;
  });
  return `readonly [${values.join(", ")}]`;
}

/**
 * Generates the virtual type contract shared by the current-user server and app boundaries.
 *
 * The selected Directus shape is derived from the configured field tuple. When the effective
 * configuration contains a mapper, its concrete return type becomes the response exposed by
 * `useDirectusUser()` without importing executable configuration into the client bundle.
 *
 * @param fields Resolved Directus current-user field selection.
 * @param mapperConfigFile Executable config source when it owns the effective mapper.
 * @param useGeneratedDirectusUser Whether `#directus` provides the generated user interface.
 * @returns Generated type declaration module.
 */
export function generateDirectusUserTypeDeclaration(
  fields: readonly UserFieldSelection[],
  mapperConfigFile?: string,
  useGeneratedDirectusUser = false
): string {
  const directusUserType = useGeneratedDirectusUser ? "DirectusUser" : "DirectusUser<Schema>";
  const selectedUserType = fields.length
    ? [
        `type DirectusUserFieldsQuery = { fields: ${generateUserFieldsType(fields)} };`,
        `type DirectusSelectedUser = ReadUserOutput<Schema, DirectusUserFieldsQuery, ${directusUserType}>;`
      ].join("\n")
    : "type DirectusSelectedUser = Record<string, unknown>;";
  const mapperType = mapperConfigFile
    ? [
        `type DirectusConfigSource = typeof import(${JSON.stringify(mapperConfigFile)})["default"];`,
        "type DirectusUserConfig = DirectusConfigSource extends { client?: { auth?: { user?: infer User } } }",
        "  ? User",
        "  : never;",
        "type DirectusUserMapper = DirectusUserConfig extends { mapper: infer Mapper } ? Mapper : never;",
        "type ResolvedDirectusUserResponse = DirectusUserMapper extends (...args: never[]) => infer Result",
        "  ? Result",
        "  : DirectusSelectedUser;"
      ].join("\n")
    : "type ResolvedDirectusUserResponse = DirectusSelectedUser;";

  return [
    "// Generated by @onderwijsin/nuxt-directus-client",
    useGeneratedDirectusUser
      ? 'import type { ReadUserOutput } from "@directus/sdk";\nimport type { DirectusUser, Schema } from "#directus";'
      : 'import type { DirectusUser, ReadUserOutput } from "@directus/sdk";\nimport type { Schema } from "#directus";',
    "",
    selectedUserType,
    mapperType,
    "",
    "export type SelectedDirectusUser = DirectusSelectedUser;",
    "export type DirectusUserResponse = ResolvedDirectusUserResponse;",
    ""
  ].join("\n");
}
