import type { UserFieldSelection } from "@onderwijsin/nuxt-directus-config/schema";

/**
 * Generates the declaration for the configured current-user projection.
 * @param fields Resolved Directus field selection.
 * @param configFile Optional executable config source path for mapper inference.
 * @returns Generated TypeScript declaration source.
 */
export function generateDirectusUserTypeDeclaration(
  fields: readonly UserFieldSelection[],
  configFile?: string
): string {
  const fieldsSource = JSON.stringify(fields, null, 2);
  const mappedType = configFile
    ? [
        `type DirectusConfigSource = typeof import(${JSON.stringify(configFile)})["default"];`,
        "type DirectusUserMapper = DirectusConfigSource extends { client?: { auth?: { user?: { mapper?: infer Mapper } } } }",
        "  ? Mapper extends (...args: never[]) => infer Result ? Result : never",
        "  : never;"
      ].join("\n")
    : "";
  const projection = configFile
    ? "DirectusUserMapper extends never ? DirectusUserFields : DirectusUserMapper"
    : "DirectusUserFields";

  return [
    "// Generated by @onderwijsin/nuxt-directus-client",
    'import type { DirectusUser, Query, ReadUserOutput } from "@directus/sdk";',
    'import type { Schema } from "#directus";',
    "",
    `const directusUserFields = ${fieldsSource} as const;`,
    "type DirectusUserFields = ReadUserOutput<Schema, { fields: typeof directusUserFields }, DirectusUser<Schema>>;",
    mappedType,
    'declare module "#directus-user" {',
    `  export type DirectusUserProjection = ${projection};`,
    "}",
    "export {};",
    ""
  ].join("\n");
}
