import type { UserFieldSelection } from "@onderwijsin/nuxt-directus-config/schema";

function generateUserFieldObjectType(field: Record<string, readonly UserFieldSelection[]>): string {
  const members = Object.entries(field).map(
    ([key, nestedFields]) =>
      `readonly ${JSON.stringify(key)}: ${generateUserFieldsType(nestedFields)};`
  );
  return `{ ${members.join(" ")} }`;
}

function generateUserFieldsType(fields: readonly UserFieldSelection[]): string {
  const values = fields.map((field) => {
    if (typeof field === "string") return JSON.stringify(field);
    return generateUserFieldObjectType(field);
  });
  return `readonly [${values.join(", ")}]`;
}

/**
 * Generates the declaration for the configured current-user projection.
 * @param fields Resolved Directus field selection.
 * @param configFile Optional executable config source path for mapper inference.
 * @returns Generated TypeScript declaration source.
 */
export function generateDirectusUserTypeDeclaration(
  fields: readonly UserFieldSelection[],
  configFile?: string
): string {
  const fieldsType = generateUserFieldsType(fields);
  const mappedType = configFile
    ? [
        `type DirectusConfigSource = typeof import(${JSON.stringify(configFile)})["default"];`,
        "type DirectusUserMapper = DirectusConfigSource extends { client?: { auth?: { user?: { mapper?: infer Mapper } } } }",
        "  ? Mapper extends (...args: never[]) => infer Result ? Result : never",
        "  : never;"
      ].join("\n")
    : "";
  const projection = configFile
    ? "DirectusUserMapper extends never ? DirectusUserFields : DirectusUserMapper"
    : "DirectusUserFields";

  return [
    "// Generated by @onderwijsin/nuxt-directus-client",
    'import type { DirectusUser, Query, ReadUserOutput } from "@directus/sdk";',
    'import type { Schema } from "#directus";',
    "",
    `type DirectusUserFieldsQuery = { fields: ${fieldsType} };`,
    "type DirectusUserFields = ReadUserOutput<Schema, DirectusUserFieldsQuery, DirectusUser<Schema>>;",
    mappedType,
    'declare module "#directus-user" {',
    `  export type DirectusUserProjection = ${projection};`,
    "}",
    "export {};",
    ""
  ].join("\n");
}

/**
 * Generates the server-only executable mapper source for the effective user projection.
 * @param configFile Shared executable config source path.
 * @param enabled Whether the shared user projection is effective.
 * @returns Virtual module source.
 */
export function generateDirectusUserConfigSource(
  configFile: string | undefined,
  enabled: boolean
): string {
  if (!configFile || !enabled) return "export default undefined;\n";
  return [
    `import config from ${JSON.stringify(configFile)};`,
    "export default config.client?.auth?.user;",
    ""
  ].join("\n");
}
