import { createError, defineEventHandler, getRouterParam, handleCors } from "h3";

import { createEditorComponentMetadata } from "./metadata";
import type { EditorComponentSource } from "./metadata";

/**
 * Creates the set-aware metadata endpoint around a generated component-meta registry.
 * @param componentMeta Registry generated by `nuxt-component-meta`.
 * @param rendererComponents All discovered renderer node and Nuxt component names.
 * @param componentSets Configured component allowlists.
 * @param corsOrigin Origins allowed to read metadata from a browser.
 * @returns An H3 event handler serving the selected metadata array.
 */
export function createComponentMetadataHandler(
  componentMeta: unknown,
  rendererComponents: EditorComponentSource[],
  componentSets: Record<string, string[]>,
  corsOrigin: "*" | "null" | string[]
) {
  return defineEventHandler((event) => {
    if (handleCors(event, { origin: corsOrigin, methods: ["GET"] })) return;

    const componentSet = getRouterParam(event, "componentSet");
    const componentNames = componentSet ? componentSets[componentSet] : undefined;

    if (componentSet && !componentNames) {
      throw createError({
        statusCode: 404,
        statusMessage: `Unknown Markdown renderer component set: ${componentSet}`
      });
    }

    const components = componentNames
      ? rendererComponents.filter(({ name }) => componentNames.includes(name))
      : rendererComponents;
    return createEditorComponentMetadata(componentMeta, components);
  });
}
