import { fromEntries, isArray, isRecord, isString } from "@onderwijsin/nuxt-module-utils/shared";

interface EditorPropertyMetadata {
  name: string;
  type: "array" | "boolean" | "number" | "string";
  description?: string;
  required?: boolean;
  default?: unknown;
  values?: string[];
  tags?: { name: string; text?: string }[];
}

interface EditorComponentMetadata {
  name: string;
  label: string;
  description?: string;
  nodeType: "block" | "inline";
  props: Record<string, EditorPropertyMetadata>;
  slots: string[];
}

function resolveEditorType(type: unknown): EditorPropertyMetadata["type"] {
  if (!isString(type)) return "string";
  if (type.includes("[]") || type.includes("Array<")) return "array";
  if (type.includes("boolean")) return "boolean";
  if (type.includes("number")) return "number";
  return "string";
}

function resolveValues(schema: unknown): string[] | undefined {
  if (!isRecord(schema) || schema.kind !== "enum" || !isArray(schema.schema)) return undefined;
  const values = schema.schema.flatMap((entry) =>
    isRecord(entry) && entry.kind === "literal" && isString(entry.value) ? [entry.value] : []
  );
  return values.length ? values : undefined;
}

function resolveDefault(value: unknown): unknown {
  if (!isString(value)) return value;
  if (value === "true") return true;
  if (value === "false") return false;
  const numeric = Number(value);
  if (value.trim() !== "" && Number.isFinite(numeric)) return numeric;
  return value.replace(/^['"]|['"]$/g, "");
}

function resolveTags(value: unknown): { name: string; text?: string }[] | undefined {
  if (!isArray(value)) return undefined;
  const tags = value.flatMap((tag) => {
    if (!isRecord(tag) || !isString(tag.name)) return [];
    return [{ name: tag.name, ...(isString(tag.text) ? { text: tag.text } : {}) }];
  });
  return tags.length ? tags : undefined;
}

function transformProperty(value: unknown): EditorPropertyMetadata | undefined {
  if (!isRecord(value) || !isString(value.name)) return undefined;
  const type = resolveEditorType(value.type);
  return {
    name: value.name,
    type,
    ...(isString(value.description) && value.description ? { description: value.description } : {}),
    ...(value.required === true ? { required: true } : {}),
    ...(value.default !== undefined ? { default: resolveDefault(value.default) } : {}),
    ...(resolveValues(value.schema) ? { values: resolveValues(value.schema) } : {}),
    ...(resolveTags(value.tags) ? { tags: resolveTags(value.tags) } : {})
  };
}

function createPropertyEntry(property: EditorPropertyMetadata): [string, EditorPropertyMetadata] {
  return [property.name, property];
}

/**
 * Converts Nuxt component metadata to the Directus Markdown editor contract.
 * @param registry Component registry generated by nuxt-component-meta.
 * @param componentNames Renderer component names to expose.
 * @returns Directus Markdown editor component metadata.
 */
export function createEditorComponentMetadata(
  registry: unknown,
  componentNames: string[]
): { components: EditorComponentMetadata[] } {
  if (!isRecord(registry)) return { components: [] };

  const components = componentNames.flatMap((name) => {
    if (name === "Reference") return [];
    const component = registry[name];
    if (!isRecord(component) || !isRecord(component.meta)) return [];
    const props = isArray(component.meta.props)
      ? component.meta.props.flatMap((value) => {
          const property = transformProperty(value);
          return property ? [createPropertyEntry(property)] : [];
        })
      : [];
    const slots = isArray(component.meta.slots)
      ? component.meta.slots.flatMap((slot) =>
          isRecord(slot) && isString(slot.name) ? [slot.name] : []
        )
      : [];

    return [
      {
        name,
        label: name,
        ...(isString(component.meta.description) && component.meta.description
          ? { description: component.meta.description }
          : {}),
        nodeType: slots.length ? "block" : "inline",
        props: fromEntries(props),
        slots
      } satisfies EditorComponentMetadata
    ];
  });

  return { components };
}
