import { existsSync, readFileSync, writeFileSync } from "node:fs";

import { generateDirectusTypes } from "directus-sdk-typegen";
import {
  attempt,
  isDefined,
  isFiniteNumber,
  isNonBlankString,
  isRecord,
  isString
} from "@onderwijsin/nuxt-module-utils/shared";
import { hash } from "ohash";

import type { ResolvedModuleOptions } from "../types/options";

/** The pinned generator version recorded in development cache manifests. */
export const DIRECTUS_TYPEGEN_VERSION = "0.2.1";

/** Metadata supplied to an advanced consumer typegen transform. */
export interface TypegenTransformContext {
  directusUrl: string;
  generatorVersion: string;
  collections: readonly string[];
  rules: Readonly<Record<string, Readonly<Record<string, string>>>>;
}

/** Supported build-time typegen transform. */
export type TypegenTransform = (source: string, context: TypegenTransformContext) => string;

/** Options used to generate, normalize, and cache a Directus declaration. */
export interface GenerateDirectusTypesOptions {
  directusUrl: string;
  directusToken: string;
  augmentations: ResolvedModuleOptions["typegen"]["augmentations"];
  rules: ResolvedModuleOptions["typegen"]["rules"];
  transform?: TypegenTransform;
  log?: TypegenLogger;
}

/** Development-only manifest for a generated declaration. It contains no credentials. */
export interface TypegenCacheManifest {
  generatorVersion: string;
  baseUrlFingerprint: string;
  optionsFingerprint: string;
  generatedAt: number;
  source: string;
}

/** Minimal logger contract used by the build-time template. */
export interface TypegenLogger {
  warn(message: string): void;
  error(message: string): void;
}

interface InterfaceDeclaration {
  name: string;
  bodyStart: number;
  bodyEnd: number;
  fields: FieldDeclaration[];
}

interface FieldDeclaration {
  name: string;
  optional: boolean;
  type: string;
  nameStart: number;
  fieldEnd: number;
  documentationStart: number;
  documentation: string;
}

interface SourceSpan {
  start: number;
  end: number;
}

const TYPE_NAME_OVERRIDES: Readonly<Record<string, string>> = {
  CandidateStatuse: "CandidateStatus"
};

const HEADER_COMMENT = `/**
 * This file is auto-generated by @onderwijsin/nuxt-directus.
 * Do not edit this file directly.
 */

`;

/**
 * Generates the raw Directus declaration and applies only explicitly enabled transforms.
 *
 * @param options Build-time generator and normalization options.
 * @returns The deterministic generated declaration source.
 */
export async function generateDirectusTypesFile(
  options: GenerateDirectusTypesOptions
): Promise<string> {
  if (!options.directusUrl || !options.directusToken) {
    throw new Error("Directus typegen requires both baseUrl and typegen.introspectionToken.");
  }

  const result = await attempt(async () => {
    const generated = await generateDirectusTypes({
      directusUrl: options.directusUrl,
      directusToken: options.directusToken
    });
    const normalized = applyTypegenTransforms(generated, options);
    const source = `${HEADER_COMMENT}${normalized.trim()}\n`;
    return source;
  });
  if (isString(result.data)) {
    return result.data;
  }
  options.log?.error("Directus schema type generation failed.");
  throw result.error;
}

/**
 * Resolves the declaration emitted by Nuxt's type template, including development-only caching.
 *
 * @param options Template generation context.
 * @returns Generated or cached declaration source.
 */
export async function resolveDirectusTypegenDeclaration(options: {
  directusUrl: string;
  directusToken?: string;
  augmentations: ResolvedModuleOptions["typegen"]["augmentations"];
  rules: ResolvedModuleOptions["typegen"]["rules"];
  transform?: TypegenTransform;
  cacheFile: string;
  generatedFile: string;
  maxAge: number;
  isDevelopment: boolean;
  isCI: boolean;
  log: TypegenLogger;
}): Promise<string> {
  const hasAnyCredential =
    isNonBlankString(options.directusUrl) || isNonBlankString(options.directusToken);
  if (!hasAnyCredential) {
    const existing = readExistingDeclaration(options.generatedFile);
    if (isDefined(existing)) return existing;
    options.log.warn(
      "Skipping Directus type generation: configure directus.baseUrl and directus.typegen.introspectionToken."
    );
    return "export interface Schema {}\n";
  }
  if (!options.directusUrl || !options.directusToken) {
    if (options.isDevelopment && !options.isCI) {
      options.log.warn(
        "Directus type generation is configured incompletely; using the previous declaration or an empty Schema in development."
      );
      const existing = readExistingDeclaration(options.generatedFile);
      return isDefined(existing) ? existing : "export interface Schema {}\n";
    }
    throw new Error(
      "Directus type generation requires both directus.baseUrl and directus.typegen.introspectionToken."
    );
  }

  const fingerprints = createTypegenFingerprint(options.directusUrl, options);
  const fingerprint = {
    ...fingerprints,
    generatorVersion: DIRECTUS_TYPEGEN_VERSION,
    generatedAt: 0,
    source: ""
  } satisfies TypegenCacheManifest;
  const cached = await readTypegenCache(
    options.cacheFile,
    options.generatedFile,
    fingerprint,
    options.maxAge,
    options.isDevelopment,
    options.isCI
  );
  if (isDefined(cached)) {
    return cached;
  }

  const source = await generateDirectusTypesFile({
    directusUrl: options.directusUrl,
    directusToken: options.directusToken,
    augmentations: options.augmentations,
    rules: options.rules,
    transform: options.transform,
    log: options.log
  });
  if (options.isDevelopment && !options.isCI) {
    await writeTypegenCache(options.cacheFile, {
      ...fingerprint,
      generatedAt: Date.now(),
      source
    });
  }
  return source;
}

/**
 * Applies the named augmentation registry, consumer rules, and final custom transform.
 *
 * @param source Generator output.
 * @param options Transform options.
 * @returns Rewritten declaration source.
 */
export function applyTypegenTransforms(
  source: string,
  options: Pick<GenerateDirectusTypesOptions, "augmentations" | "rules" | "transform"> & {
    directusUrl?: string;
  }
): string {
  let result = source;

  if (options.augmentations.removeEnums) result = removeEnums(result);
  if (options.augmentations.replaceAnyWithUnknown) result = replaceAnyWithUnknown(result);
  if (options.augmentations.replaceJsonWithJSON) result = replaceJsonWithJSON(result);
  if (options.augmentations.applyTypeNameOverrides) result = applyTypeNameOverrides(result);
  if (options.augmentations.makeNonNullableOptionalsRequired) {
    result = makeNonNullableOptionalsRequired(result);
  }
  if (options.augmentations.mergeJsDocs) result = mergeJsDocs(result);

  result = applyRules(result, options.rules);
  if (isDefined(options.transform)) {
    const interfaces = scanInterfaces(result);
    result = options.transform(result, {
      directusUrl: isDefined(options.directusUrl) ? options.directusUrl : "",
      generatorVersion: DIRECTUS_TYPEGEN_VERSION,
      collections: interfaces.map((declaration) => declaration.name),
      rules: options.rules
    });
    if (!isString(result)) {
      throw new Error("directus.typegen.transform must return a string declaration.");
    }
  }

  return result;
}

/**
 * Reads a declaration's interfaces and fields using balanced delimiters.
 *
 * @param source TypeScript declaration source.
 * @returns Interface and field spans used by all source rewrites.
 */
export function scanInterfaces(source: string): InterfaceDeclaration[] {
  const declarations: InterfaceDeclaration[] = [];
  const interfacePattern = /\b(?:export\s+)?interface\s+([A-Za-z_$][\w$]*)\s*\{/g;
  let match: RegExpExecArray | null;

  while ((match = interfacePattern.exec(source))) {
    const bodyStart = match.index + match[0].length;
    const bodyEnd = findMatchingDelimiter(source, bodyStart - 1, "{", "}");
    if (bodyEnd < 0) break;
    declarations.push({
      name: match[1]!,
      bodyStart,
      bodyEnd,
      fields: scanFields(source, bodyStart, bodyEnd)
    });
    interfacePattern.lastIndex = bodyEnd + 1;
  }

  return declarations;
}

/**
 * Scans direct fields inside one interface body, preserving multiline type boundaries.
 *
 * @param source TypeScript declaration source.
 * @param bodyStart Interface body opening boundary.
 * @param bodyEnd Interface body closing boundary.
 * @returns Field declarations found in the interface body.
 */
function scanFields(source: string, bodyStart: number, bodyEnd: number): FieldDeclaration[] {
  const fields: FieldDeclaration[] = [];
  let cursor = bodyStart;

  while (cursor < bodyEnd) {
    const lineStart = cursor;
    const lineEnd = source.indexOf("\n", cursor);
    const boundary = lineEnd < 0 || lineEnd > bodyEnd ? bodyEnd : lineEnd;
    const line = source.slice(lineStart, boundary);
    const fieldMatch = /^(\s*)([A-Za-z_$][\w$]*|(['"])(?:\\.|(?!\3).)*\3)(\?)?\s*:/.exec(line);

    if (!fieldMatch) {
      cursor = boundary + 1;
      continue;
    }

    const name = fieldMatch[2]!.replace(/^['"]|['"]$/g, "");
    const nameStart = lineStart + fieldMatch[1]!.length;
    const colon = lineStart + fieldMatch[0].lastIndexOf(":");
    const fieldEnd = findStatementEnd(source, colon + 1, bodyEnd);
    if (fieldEnd < 0) break;

    const documentationStart = findDocumentationStart(source, nameStart, bodyStart);
    fields.push({
      name,
      optional: isDefined(fieldMatch[4]),
      type: source
        .slice(colon + 1, fieldEnd)
        .replace(/;\s*$/, "")
        .trim(),
      nameStart,
      fieldEnd,
      documentationStart,
      documentation: source.slice(documentationStart, nameStart)
    });
    cursor = fieldEnd + 1;
  }

  return fields;
}

/**
 * Finds contiguous JSDoc blocks immediately preceding a declaration field.
 *
 * @param source TypeScript declaration source.
 * @param start Field name start offset.
 * @param lowerBound Interface body start offset.
 * @returns Start offset of the contiguous documentation region.
 */
function findDocumentationStart(source: string, start: number, lowerBound: number): number {
  let cursor = start;
  while (cursor > lowerBound) {
    while (cursor > lowerBound && /\s/.test(source[cursor - 1]!)) cursor -= 1;
    if (!source.slice(Math.max(lowerBound, cursor - 2), cursor).endsWith("*/")) break;
    const blockStart = source.lastIndexOf("/**", cursor - 3);
    if (blockStart < lowerBound) break;
    cursor = blockStart;
  }
  return cursor;
}

/**
 * Finds a field semicolon while ignoring nested types, strings, and comments.
 *
 * @param source TypeScript declaration source.
 * @param start Type expression start offset.
 * @param upperBound Interface body end offset.
 * @returns Semicolon offset, or `-1` when the declaration is incomplete.
 */
function findStatementEnd(source: string, start: number, upperBound: number): number {
  let braces = 0;
  let brackets = 0;
  let parentheses = 0;
  let quote = "";
  let lineComment = false;
  let blockComment = false;

  for (let index = start; index < upperBound; index += 1) {
    const current = source[index]!;
    const nextValue = source[index + 1];
    const next = isDefined(nextValue) ? nextValue : "";

    if (lineComment) {
      if (current === "\n") lineComment = false;
      continue;
    }
    if (blockComment) {
      if (current === "*" && next === "/") {
        blockComment = false;
        index += 1;
      }
      continue;
    }
    if (quote) {
      if (current === "\\") index += 1;
      else if (current === quote) quote = "";
      continue;
    }
    if (current === "/" && next === "/") {
      lineComment = true;
      index += 1;
      continue;
    }
    if (current === "/" && next === "*") {
      blockComment = true;
      index += 1;
      continue;
    }
    if (current === '"' || current === "'" || current === "`") {
      quote = current;
      continue;
    }
    if (current === "{") braces += 1;
    else if (current === "}") braces -= 1;
    else if (current === "[") brackets += 1;
    else if (current === "]") brackets -= 1;
    else if (current === "(") parentheses += 1;
    else if (current === ")") parentheses -= 1;
    else if (current === ";" && braces === 0 && brackets === 0 && parentheses === 0) return index;
  }

  return -1;
}

/**
 * Finds the matching closing delimiter while ignoring nested strings and comments.
 *
 * @param source TypeScript declaration source.
 * @param start Opening delimiter offset.
 * @param opening Opening delimiter.
 * @param closing Closing delimiter.
 * @returns Matching closing delimiter offset, or `-1` when incomplete.
 */
function findMatchingDelimiter(
  source: string,
  start: number,
  opening: string,
  closing: string
): number {
  let depth = 0;
  let quote = "";
  let lineComment = false;
  let blockComment = false;

  for (let index = start; index < source.length; index += 1) {
    const current = source[index]!;
    const nextValue = source[index + 1];
    const next = isDefined(nextValue) ? nextValue : "";
    if (lineComment) {
      if (current === "\n") lineComment = false;
      continue;
    }
    if (blockComment) {
      if (current === "*" && next === "/") {
        blockComment = false;
        index += 1;
      }
      continue;
    }
    if (quote) {
      if (current === "\\") index += 1;
      else if (current === quote) quote = "";
      continue;
    }
    if (current === "/" && next === "/") {
      lineComment = true;
      index += 1;
      continue;
    }
    if (current === "/" && next === "*") {
      blockComment = true;
      index += 1;
      continue;
    }
    if (current === '"' || current === "'" || current === "`") {
      quote = current;
      continue;
    }
    if (current === opening) depth += 1;
    if (current === closing) {
      depth -= 1;
      if (depth === 0) return index;
    }
  }

  return -1;
}

/**
 * Rewrites field type spans using a scanner-provided field declaration.
 *
 * @param source TypeScript declaration source.
 * @param rewrite Field rewrite callback.
 * @returns Rewritten declaration source.
 */
function replaceFieldTypes(
  source: string,
  rewrite: (field: FieldDeclaration, declaration: InterfaceDeclaration) => string | undefined
): string {
  const replacements: Array<{ span: SourceSpan; value: string }> = [];
  for (const declaration of scanInterfaces(source)) {
    for (const field of declaration.fields) {
      const replacement = rewrite(field, declaration);
      if (isDefined(replacement)) {
        const colon = source.indexOf(":", field.nameStart);
        if (colon < 0 || colon > field.fieldEnd) continue;
        replacements.push({
          span: { start: colon + 1, end: field.fieldEnd },
          value: ` ${replacement};`
        });
      }
    }
  }
  return applyReplacements(source, replacements);
}

/**
 * Applies non-overlapping source replacements from right to left.
 *
 * @param source TypeScript declaration source.
 * @param replacements Inclusive source spans and replacement values.
 * @returns Rewritten declaration source.
 */
function applyReplacements(
  source: string,
  replacements: Array<{ span: SourceSpan; value: string }>
): string {
  return replacements
    .sort((left, right) => right.span.start - left.span.start)
    .reduce((result, replacement) => {
      return `${result.slice(0, replacement.span.start)}${replacement.value}${result.slice(replacement.span.end + 1)}`;
    }, source);
}

/**
 * Removes export enum declarations using balanced declaration boundaries.
 *
 * @param source TypeScript declaration source.
 * @returns Source without enum declarations.
 */
function removeEnums(source: string): string {
  const spans: SourceSpan[] = [];
  const enumPattern = /\bexport\s+enum\s+[A-Za-z_$][\w$]*\s*\{/g;
  let match: RegExpExecArray | null;
  while ((match = enumPattern.exec(source))) {
    const end = findMatchingDelimiter(source, match.index + match[0].length - 1, "{", "}");
    if (end < 0) break;
    spans.push({ start: match.index, end });
    enumPattern.lastIndex = end + 1;
  }
  return applyReplacements(
    source,
    spans.map((span) => ({ span, value: "" }))
  );
}

/**
 * Replaces permissive generated Record values with unknown.
 *
 * @param source TypeScript declaration source.
 * @returns Source with selected Record values rewritten.
 */
function replaceAnyWithUnknown(source: string): string {
  return replaceFieldTypes(source, (field) =>
    field.type.replace(/Record\s*<([^,]+),\s*any>/g, "Record<$1, unknown>")
  );
}

/**
 * Replaces generated quoted JSON type literals with the JSON type.
 *
 * @param source TypeScript declaration source.
 * @returns Source with selected JSON literals rewritten.
 */
function replaceJsonWithJSON(source: string): string {
  return replaceFieldTypes(source, (field) => field.type.replace(/(['"])json\1/g, "JSON"));
}

/**
 * Applies reviewed generated type-name corrections.
 *
 * @param source TypeScript declaration source.
 * @returns Source with known type-name corrections applied.
 */
function applyTypeNameOverrides(source: string): string {
  return replaceFieldTypes(source, (field) => {
    let type = field.type;
    for (const [wrong, correct] of Object.entries(TYPE_NAME_OVERRIDES)) {
      type = type.replace(new RegExp(`\\b${wrong}\\b`, "g"), correct);
    }
    return type;
  }).replace(/(interface\s+)CandidateStatuse\b/g, "$1CandidateStatus");
}

/**
 * Converts simple non-nullable optional fields to required fields.
 *
 * @param source TypeScript declaration source.
 * @returns Source with selected optional markers removed.
 */
function makeNonNullableOptionalsRequired(source: string): string {
  const replacements: Array<{ span: SourceSpan; value: string }> = [];
  for (const declaration of scanInterfaces(source)) {
    for (const field of declaration.fields) {
      const complex = /[({[(]|=>/.test(field.type.trim());
      if (!field.optional || field.type.includes("null") || complex) continue;
      const optionalEnd = source.indexOf("?", field.nameStart);
      if (optionalEnd < 0 || optionalEnd > field.fieldEnd) continue;
      replacements.push({ span: { start: optionalEnd, end: optionalEnd }, value: "" });
      if (!field.documentation.includes("@required")) {
        const indentStart = source.lastIndexOf("\n", field.documentationStart) + 1;
        const indentation = source.slice(indentStart, field.nameStart).match(/^\s*/);
        const indent = isDefined(indentation?.[0]) ? indentation[0] : "";
        replacements.push({
          span: { start: field.documentationStart, end: field.documentationStart - 1 },
          value: `${indent}/** @required */\n`
        });
      }
    }
  }
  return applyReplacements(source, replacements);
}

/**
 * Merges adjacent JSDoc tag blocks and removes duplicate tags.
 *
 * @param source TypeScript declaration source.
 * @returns Source with selected documentation blocks merged.
 */
function mergeJsDocs(source: string): string {
  const replacements: Array<{ span: SourceSpan; value: string }> = [];
  const blocks = scanJsDocBlocks(source);
  for (let index = 0; index < blocks.length - 1; index += 1) {
    const first = blocks[index]!;
    const second = blocks[index + 1]!;
    if (!/^\s*$/.test(source.slice(first.end, second.start))) continue;
    const tags = [...first.tags, ...second.tags];
    const uniqueTags = [...new Set(tags)];
    replacements.push({
      span: { start: first.start, end: second.end - 1 },
      value: `/**\n${uniqueTags.map((tag) => ` * ${tag}`).join("\n")}\n */`
    });
    index += 1;
  }
  return applyReplacements(source, replacements);
}

/**
 * Scans JSDoc blocks and extracts their tag lines.
 *
 * @param source TypeScript declaration source.
 * @returns JSDoc block spans and normalized tags.
 */
function scanJsDocBlocks(source: string): Array<{ start: number; end: number; tags: string[] }> {
  const blocks: Array<{ start: number; end: number; tags: string[] }> = [];
  let cursor = 0;
  while (cursor < source.length) {
    const start = source.indexOf("/**", cursor);
    if (start < 0) break;
    const close = source.indexOf("*/", start + 3);
    if (close < 0) break;
    const body = source.slice(start + 3, close);
    const tags = body
      .split("\n")
      .map((line) => line.replace(/^\s*\*?\s*/, "").trim())
      .filter((line) => line.startsWith("@"));
    blocks.push({ start, end: close + 2, tags });
    cursor = close + 2;
  }
  return blocks;
}

/**
 * Applies validated collection and field type overrides.
 *
 * @param source TypeScript declaration source.
 * @param rules Collection and field type rules.
 * @returns Rewritten declaration source.
 * @throws When a configured collection or field is absent.
 */
function applyRules(source: string, rules: ResolvedModuleOptions["typegen"]["rules"]): string {
  const declarations = scanInterfaces(source);
  const byName = new Map(declarations.map((declaration) => [declaration.name, declaration]));
  const replacements: Array<{ span: SourceSpan; value: string }> = [];

  for (const [collection, fields] of Object.entries(rules)) {
    const declaration = byName.get(collection);
    if (!declaration) {
      throw new Error(`directus.typegen.rules references missing collection "${collection}".`);
    }
    const fieldMap = new Map(declaration.fields.map((field) => [field.name, field]));
    for (const [fieldName, type] of Object.entries(fields)) {
      const field = fieldMap.get(fieldName);
      if (!field) {
        throw new Error(
          `directus.typegen.rules references missing field "${collection}.${fieldName}".`
        );
      }
      const colon = source.indexOf(":", field.nameStart);
      if (colon < 0 || colon > field.fieldEnd) continue;
      replacements.push({ span: { start: colon + 1, end: field.fieldEnd }, value: ` ${type};` });
    }
  }

  return applyReplacements(source, replacements);
}

/**
 * Reads a previously generated declaration only when it contains usable source.
 *
 * Nuxt can create the destination file before invoking `getContents`; returning that empty file
 * makes Nuxt reject the template with `NUXT_B1001`.
 *
 * @param generatedFile Generated declaration path.
 * @returns Non-blank declaration source, or `undefined` when unavailable.
 */
function readExistingDeclaration(generatedFile: string): string | undefined {
  if (!existsSync(generatedFile)) return undefined;
  const source = readFileSync(generatedFile, "utf8");
  return isNonBlankString(source) ? source : undefined;
}

/**
 * Creates a credential-free fingerprint for development cache validation.
 *
 * @param directusUrl Directus base URL.
 * @param options Normalization and rule options.
 * @returns A stable SHA-256 fingerprint.
 */
export function createTypegenFingerprint(
  directusUrl: string,
  options: Pick<GenerateDirectusTypesOptions, "augmentations" | "rules" | "transform">
): { baseUrlFingerprint: string; optionsFingerprint: string } {
  return {
    baseUrlFingerprint: hash(directusUrl),
    optionsFingerprint: hash({
      augmentations: options.augmentations,
      rules: options.rules,
      transform: isDefined(options.transform) ? options.transform.toString() : null,
      generatorVersion: DIRECTUS_TYPEGEN_VERSION
    })
  };
}

/**
 * Reads a valid development cache manifest and returns its generated source.
 *
 * @param cacheFile Manifest path.
 * @param generatedFile Generated declaration path used as a fallback for older manifests.
 * @param fingerprint Expected cache fingerprint.
 * @param maxAge Maximum cache age in milliseconds.
 * @param isDevelopment Whether Nuxt is running in development mode.
 * @param isCI Whether CI mode is active.
 * @returns Cached declaration source, or `undefined` when regeneration is required.
 */
export async function readTypegenCache(
  cacheFile: string,
  generatedFile: string,
  fingerprint: TypegenCacheManifest,
  maxAge: number,
  isDevelopment: boolean,
  isCI: boolean
): Promise<string | undefined> {
  if (!isDevelopment || isCI || !existsSync(cacheFile)) return undefined;
  const result = await attempt(() => JSON.parse(readFileSync(cacheFile, "utf8")) as unknown);
  if (!isDefined(result.data) || !isTypegenCacheManifest(result.data)) return undefined;
  const manifest = result.data;
  if (
    manifest.generatorVersion !== fingerprint.generatorVersion ||
    manifest.baseUrlFingerprint !== fingerprint.baseUrlFingerprint ||
    manifest.optionsFingerprint !== fingerprint.optionsFingerprint ||
    Date.now() - manifest.generatedAt >= maxAge
  ) {
    return undefined;
  }
  if (manifest.source) return manifest.source;
  return existsSync(generatedFile) ? readFileSync(generatedFile, "utf8") : undefined;
}

/**
 * Writes a development cache manifest without exposing the introspection token.
 *
 * @param cacheFile Manifest path.
 * @param manifest Manifest contents.
 */
export async function writeTypegenCache(
  cacheFile: string,
  manifest: TypegenCacheManifest
): Promise<void> {
  await attempt(() => writeFileSync(cacheFile, JSON.stringify(manifest, null, 2)));
}

/**
 * Validates the credential-free cache manifest shape.
 *
 * @param value Unknown parsed JSON value.
 * @returns Whether the value is a valid cache manifest.
 */
function isTypegenCacheManifest(value: unknown): value is TypegenCacheManifest {
  if (!isRecord(value)) return false;
  return (
    isString(value.generatorVersion) &&
    isString(value.baseUrlFingerprint) &&
    isString(value.optionsFingerprint) &&
    isFiniteNumber(value.generatedAt) &&
    isString(value.source)
  );
}
