/**
 * Stable top-of-file fixture from the production Directus schema.
 * Keep this fixture intentionally limited to the extension metadata contract; do not commit the
 * complete production data model.
 */
export const productionSchema = `/**
 * This file is auto-generated by @onderwijsin/nuxt-directus.
 * Do not edit this file directly.
 */

export interface ExtensionSeoMetadata {
    title?: string;
    meta_description?: string;
    og_image?: string;
    additional_fields?: Record<string, unknown>;
    sitemap?: {
        change_frequency: 'always' | 'hourly' | 'daily' | 'weekly' | 'monthly' | 'yearly' | 'never';
        priority: string;
    };
    no_index?: boolean;
    no_follow?: boolean;
}

export interface Schema {
    extension_seo_metadata: ExtensionSeoMetadata[];
}
`;
