import { describe, expect, it, vi } from "vitest";

import { productionSchema } from "./fixtures/production-schema";
import { generateDirectusTypesFile } from "../src/config/typegen";

vi.mock("directus-sdk-typegen", () => ({
  generateDirectusTypes: vi.fn(async () => productionSchema)
}));

describe("Directus production-schema typegen contract", () => {
  it("preserves the stable metadata shape while applying rules and transforms", async () => {
    const source = await generateDirectusTypesFile({
      directusUrl: "https://directus.example.test",
      directusToken: "test-introspection-token",
      augmentations: {
        removeEnums: true,
        replaceAnyWithUnknown: true,
        replaceJsonWithJSON: true,
        applyTypeNameOverrides: true,
        makeNonNullableOptionalsRequired: true,
        mergeJsDocs: true
      },
      rules: {
        ExtensionSeoMetadata: {
          additional_fields: "Record<string, string>"
        }
      },
      transform: (value, context) =>
        `${value}\nexport type ExtensionSeoMetadataTitle = ExtensionSeoMetadata["title"];\n// ${context.collections.join(",")}`
    });

    expect(
      source.startsWith("/**\n * This file is auto-generated by @onderwijsin/nuxt-directus.")
    ).toBe(true);
    expect(source).toContain("export interface ExtensionSeoMetadata {");
    expect(source).toContain("title: string;");
    expect(source).toContain("additional_fields: Record<string, string>;");
    expect(source).toContain("sitemap?: {");
    expect(source).toContain("change_frequency: 'always' | 'hourly'");
    expect(source).toContain(
      'export type ExtensionSeoMetadataTitle = ExtensionSeoMetadata["title"];'
    );
    expect(source).toContain("// ExtensionSeoMetadata,Schema");
  });
});
