import type { ButtonProps } from "@nuxt/ui";

/** Runtime app configuration consumed by the theme customizer. */
export type ThemeAppConfig = {
  ui: {
    colors: Record<string, string>;
    radius: number;
  };
};

/** A button action displayed by the theme customizer confirmation dialog. */
export type ConfirmationAction = ButtonProps & {
  mode: "confirm" | "cancel";
};

/** Options accepted by the theme customizer confirmation dialog. */
export type ConfirmDialogProps = {
  title: string;
  description?: string;
  color?: ButtonProps["color"];
  actions?: ConfirmationAction[];
};

/** Public runtime configuration generated by the module entrypoint. */
export type ThemeCustomizerRuntimeConfig = {
  public: {
    themeCustomizer: {
      groups: Record<string, string[]>;
    };
  };
};
