name: Changeset status

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled]
  merge_group:

permissions: {}

concurrency:
  group: changeset-status-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  changeset_status:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      comment-body: ${{ steps.changesets.outputs.comment-body }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: Generate Changeset status
        id: changesets
        uses: changesets/action/pr-status@a45c4d594aa4e2c509dc14a9f2b3b67ba3780d0d # v1

  changeset_comment:
    needs: changeset_status
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Comment Changeset status
        uses: changesets/action/pr-comment@a45c4d594aa4e2c509dc14a9f2b3b67ba3780d0d # v1
        with:
          body: ${{ needs.changeset_status.outputs.comment-body }}

  changeset_merge_group_status:
    name: Changeset status (merge group)
    if: github.event_name == 'merge_group'
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - name: Mark Changesets status as successful
        run: echo "Changesets status is not evaluated for merge groups."
