# Scan for secrets using gitleaks
name: Gitleaks

on:
  pull_request: {}
  push: {}
  workflow_dispatch: {}
  schedule:
    # Run once a week at 4am on Sundays.
    - cron: "0 4 * * 0"

permissions:
  contents: read

jobs:
  gitleaks:
    if: ${{ github.actor != 'dependabot[bot]' }}
    name: Gitleaks
    runs-on: blacksmith-2vcpu-ubuntu-2404
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          fetch-depth: 0
      - uses: gitleaks/gitleaks-action@ff98106e4c7b2bc287b24eaf42907196329070c7 # v2
        with:
          config: .gitleaks.toml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITLEAKS_NOTIFY_USER_LIST: "@remihuigen,@joggienl"
          GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}
          GITLEAKS_VERSION: 8.29.0
